// Global using directives

global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics;
global using System.Security.Claims;
global using System.Text.RegularExpressions;
global using Azure.Core;
global using Azure.Identity;
global using ClosedXML.Excel;
global using Glenavon.JFC.WebApp;
global using Glenavon.JFC.WebApp.Models;
global using Glenavon.JFC.WebApp.Services;
global using Glenavon.JFC.WebApp.Settings;
global using Glenavon.JFC.WebApp.ViewModels;
global using HtmlAgilityPack;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.TagHelpers;
global using Microsoft.Extensions.Options;
global using Microsoft.Graph;
global using Microsoft.Graph.Models;
global using Microsoft.Graph.Users.Item.SendMail;
global using Newtonsoft.Json;
global using PdfSharpCore.Drawing;
global using PdfSharpCore.Pdf;
global using reCAPTCHA.AspNetCore;
global using SixLabors.ImageSharp;
global using SixLabors.ImageSharp.Formats.Png;
global using SixLabors.ImageSharp.PixelFormats;
global using Image = SixLabors.ImageSharp.Image;
global using WebApplication = Microsoft.AspNetCore.Builder.WebApplication;